name: Build iOS for ALTStore

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_ios_altstore:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS app (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Create unsigned .ipa for ALTStore
        run: |
          cd ios
          mkdir -p build/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ipa/Payload/
          cd build/ipa
          zip -r Gymflow.ipa Payload
          mv Gymflow.ipa ../../Gymflow.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: Gymflow-ALTStore-IPA
          path: ios/Gymflow.ipa
