name: Build iOS for ALTStore

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_ios_altstore:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Install dependencies
        run: flutter pub get

              - name: Export IPA
        run: |
          mkdir -p build/ios/ipa
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/ios/ipa


      - name: Build IPA (ad-hoc, no codesign)
        run: flutter build ipa --export-method ad-hoc --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Gymflow-ALTStore-IPA
          path: build/ios/ipa/Runner.ipa
